version: '3.8'

services:
  app-producer:
    build: Dockerfile-producer
    
  app-consumer:
    build: Dockerfile-consumer

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 15672:15672
    - 5672:5672

  redis:
    image: redis/redis-stack:7.2.0-v10
    ports:
    - 6379:6379
    - 8001:8001

  minio:
    image: bitnami/minio:2024.3.30
    ports:
    - 9000:9000
    - 9001:9001